import Line from "../../models/Line.js";

class LineSeeder {
  static async seed() {
    await Line.query().delete();

    const linesData = [
      { line: "'Scuse me while I turn up the <|REPLACE|>." },
      { line: "A rhyme for a rhyme all you're giving is <|REPLACE|>." },
      { line: "Add fuel to the fire and you'll start to <|REPLACE|>." },
      { line: "After I'm done I'll steal your <|REPLACE|>." },
      { line: "Alexa calls out my name to learn about <|REPLACE|>." },
      { line: "All of my fans, beg me to <|REPLACE|>." },
      { line: "All of your rhymes make me want to <|REPLACE|>." },
      { line: "Am I making you sweat? Do you need a <|REPLACE|>?" },
      { line: "Anyone home in there? <|REPLACE|>?" },
      { line: "Are you feeling okay? 'Cause you look a bit <|REPLACE|>." },
      { line: "Are you finished yet? I gotta go <|REPLACE|>." },
      { line: "Are you lost? Did you think this was <|REPLACE|>?" },
      { line: "As I open my mouth your heart will <|REPLACE|>." },
      { line: "As looks go, you're far from <|REPLACE|>." },
      { line: "Back yourself up and watch me <|REPLACE|>." },
      { line: "Banging on your door like a <|REPLACE|>." },
      { line: "Bet you never heard bout the birds and <|REPLACE|>." },
      { line: "Better go home before you develop a <|REPLACE|>." },
      { line: "Better speak up! You're quiet as a <|REPLACE|>." },
      { line: "Better take a seat you're looking <|REPLACE|>." },
      { line: "Bow down to me the president of the <|REPLACE|>." },
      { line: "Call me Cantankerous, I B <|REPLACE|>." },
      { line: "Call this the start of my victory <|REPLACE|>." },
      { line: "Can't get over me. I'm like a case of <|REPLACE|>." },
      { line: "Careful not to trip over your own <|REPLACE|>." },
      { line: "Check out my flow it's stronger than <|REPLACE|>." },
      { line: "Check out my grill all studded with <|REPLACE|>." },
      { line: "Check your watch it's your time to <|REPLACE|>." },
      { line: "Clack clack clack! go my heels on your <|REPLACE|>." },
      { line: "Class, is in session, my <|REPLACE|>." },
      { line: "Come get some if you think you're <|REPLACE|>." },
      { line: "Comin' at you, like a runaway <|REPLACE|>." },
      { line: "Compared to my words, yours are <|REPLACE|>." },
      { line: "Cover your eyes I'm bright like a <|REPLACE|>." },
      { line: "Cover your heads my beats drop like <|REPLACE|>." },
      { line: "Damn, kid, you talk too <|REPLACE|>." },
      { line: "Dang your last rhyme was pathetic and <|REPLACE|>." },
      { line: "Did anyone tell you that you're a <|REPLACE|>?" },
      { line: "Did I break you yet? Should we call a <|REPLACE|>?" },
      { line: "Did ya know, I'm fluent in <|REPLACE|>?" },
      { line: "Did you mess up? Should I call the <|REPLACE|>?" },
      { line: "Did you not understand me? You look <|REPLACE|>." },
      { line: "Don't come at me with that big ol' <|REPLACE|>." },
      { line: "Don't let this scare you: I'm stronger than a <|REPLACE|>." },
      { line: "Don't look now but I'm about to <|REPLACE|>." },
      { line: "Don't look now you're about to be <|REPLACE|>." },
      { line: "Don't look now: I stole your <|REPLACE|>." },
      { line: "Don't need permission to rock this <|REPLACE|>." },
      { line: "Don't rush the stage I'm coming in <|REPLACE|>." },
      { line: "Don't talk back 'less you wanna get <|REPLACE|>." },
      { line: "Don't think for a minute that you're even <|REPLACE|>." },
      { line: "Don't wake me up unless you want to get <|REPLACE|>." },
      { line: "Dropping the mic cuz your hands are too <|REPLACE|>." },
      { line: "Everybody give it up for me say <|REPLACE|>." },
      { line: "Everywhere I go fans shower me with <|REPLACE|>." },
      { line: "Everywhere I go, people, <|REPLACE|>." },
      { line: "Face it kid, you won't last a <|REPLACE|>." },
      { line: "Feel that pain? That's me kicking your <|REPLACE|>." },
      { line: "First things first: I'm better than <|REPLACE|>." },
      { line: "Flip to the end and see that I <|REPLACE|>." },
      { line: "For real are you here to sell me <|REPLACE|>?" },
      { line: "Forget about it I'm through bein' <|REPLACE|>." },
      { line: "Forget Ghostbusters for you I'd call <|REPLACE|>." },
      { line: "Frankly I'm bored. You got no <|REPLACE|>." },
      { line: "Frankly I'm disgusted by the sight of your <|REPLACE|>." },
      { line: "Freight train's comin' right at your <|REPLACE|>." },
      { line: "Gather 'round I'm about to get <|REPLACE|>." },
      { line: "Get out of my face or you'll be <|REPLACE|>." },
      { line: "Get outta my crib go back to your <|REPLACE|>." },
      { line: "Gettin' stuff done like a total <|REPLACE|>." },
      { line: "Give up your dreams, cuz I'm <|REPLACE|>." },
      { line: "Go ahead and dig a grave you're done <|REPLACE|>." },
      { line: "Go and tell your mama that you got <|REPLACE|>." },
      { line: "Go back to school kid learn some <|REPLACE|>." },
      { line: "Go on now run back to your <|REPLACE|>." },
      { line: "Gonna go home cryin' you little <|REPLACE|>." },
      { line: "Google me you'll see a picture of a <|REPLACE|>." },
      { line: "Got fire in my heart ice in my <|REPLACE|>." },
      { line: "Got somewhere to be? You look kinda <|REPLACE|>." },
      { line: "Have you ever considered a career in <|REPLACE|>?" },
      { line: "Have you ever heard you look like a <|REPLACE|>." },
      { line: "Haven't you heard? I can't be <|REPLACE|>." },
      { line: "Haven't you heard? I'm the next <|REPLACE|>." },
      { line: "Heads up, you're standing under a <|REPLACE|>." },
      { line: "Here I come, straight from the <|REPLACE|>." },
      { line: "Here, let me paint you a <|REPLACE|>." },
      { line: "Here's my message: You're guaranteed to <|REPLACE|>." },
      { line: "Here's the difference between u and <|REPLACE|>." },
      { line: "Hey, kid, get out of my <|REPLACE|>." },
      { line: "Hold on now you're 'bout to get <|REPLACE|>." },
      { line: "Hold up now, just wait a <|REPLACE|>." },
      { line: "How 'bout this? You can be my <|REPLACE|>." },
      { line: "How sad you look in your little <|REPLACE|>." },
      { line: "I ain't afraid, just bring it, <|REPLACE|>." },
      { line: "I ain't being cruel you're missing the <|REPLACE|>." },
      { line: "I ain't collectin' taxes I'm takin home <|REPLACE|>." },
      { line: "I ain't debatin' it's a fact that I <|REPLACE|>." },
      { line: "I ain't sure what you're trying to <|REPLACE|>." },
      { line: "I ain't your friend I ain't your <|REPLACE|>." },
      { line: "I always buy organic cuz I'm rich as <|REPLACE|>." },
      { line: "I always sparkle. You're dusty as a <|REPLACE|>." },
      { line: "I am the grand marshall, of <|REPLACE|>." },
      { line: "I bet the kids in school used to call you <|REPLACE|>." },
      { line: "I came here to crush and my words are <|REPLACE|>." },
      { line: "I can do it all like I told you <|REPLACE|>." },
      { line: "I can do it all, like <|REPLACE|>." },
      { line: "I can read you like a book, like <|REPLACE|>." },
      { line: "I can't hear what you say I'm deaf to <|REPLACE|>." },
      { line: "I can't listen to you it makes me <|REPLACE|>." },
      { line: "I can't listen to you. Your head's hard as <|REPLACE|>." },
      { line: "I can't stop winning you're a total <|REPLACE|>." },
      { line: "I can't think, of anyone <|REPLACE|>." },
      { line: "I come and see and conquer just like <|REPLACE|>." },
      { line: "I deliver it hot, as <|REPLACE|>." },
      { line: "I destroy city blocks like a gigantic <|REPLACE|>." },
      { line: "I didn't recognize you with all that <|REPLACE|>." },
      { line: "I don't care about you or your <|REPLACE|>." },
      { line: "I don't got pity but I can give you a <|REPLACE|>." },
      { line: "I don't mince words so let me cut to the <|REPLACE|>." },
      { line: "I don't rely on chance I make my own <|REPLACE|>." },
      { line: "I don't sweat the small stuff and you're very <|REPLACE|>." },
      { line: "I drive a Bentley, you drive a <|REPLACE|>." },
      { line: "I drive to the hoop, like <|REPLACE|>." },
      { line: "I dropped one single now I'm rich as <|REPLACE|>." },
      { line: "I feel bad for you cuz here comes my <|REPLACE|>." },
      { line: "I flow so smooth. You flow like <|REPLACE|>." },
      { line: "I got a big heart, my rhymes are full of <|REPLACE|>." },
      { line: "I got a crystal ball and I see your <|REPLACE|>." },
      { line: "I got a match: My face and your <|REPLACE|>." },
      { line: "I got big plans, I'm a <|REPLACE|>." },
      { line: "I got eight secret arms like an octo-<|REPLACE|>." },
      { line: "I got more bling than a Housewife of <|REPLACE|>." },
      { line: "I got more processing power than a <|REPLACE|>." },
      { line: "I got underwear that's sprayed with <|REPLACE|>." },
      { line: "I got words in my heart and a mic in my <|REPLACE|>." },
      { line: "I got you a hat that says 'World's Worst <|REPLACE|>.'" },
      { line: "I gotta slow down I'm getting too <|REPLACE|>." },
      { line: "I grew up in the streets. You were raised in <|REPLACE|>." },
      { line: "I hear the beat, I come out <|REPLACE|>." },
      { line: "I hear you like to spar with <|REPLACE|>." },
      { line: "I hear you talkin' like you're <|REPLACE|>." },
      { line: "I hear you talking, you sound like <|REPLACE|>." },
      { line: "I heard it's been a long time since you <|REPLACE|>." },
      { line: "I heard that you're not allowed to <|REPLACE|>." },
      { line: "I heard what you said about me! You are <|REPLACE|>!" },
      { line: "I heard what you said, that's the last <|REPLACE|>." },
      { line: "I just got appraised I'm worth 10,000 <|REPLACE|>." },
      { line: "I just stopped by on my way to the <|REPLACE|>." },
      { line: "I keep success in my pocket next to my <|REPLACE|>." },
      { line: "I knew you were coming because I smelled <|REPLACE|>." },
      { line: "I know what they mean: Mo' money mo' <|REPLACE|>." },
      { line: "I live so large, I break <|REPLACE|>." },
      { line: "I look great, you look like a <|REPLACE|>." },
      { line: "I looked you up and saw a picture of <|REPLACE|>." },
      { line: "I make new rules like a modern <|REPLACE|>." },
      { line: "I make people dance. You make people <|REPLACE|>." },
      { line: "I march to sick beats you march to <|REPLACE|>." },
      { line: "I may not be charming but I'm <|REPLACE|>." },
      { line: "I miss the days, when you were <|REPLACE|>." },
      { line: "I need a microscope your skill's so <|REPLACE|>." },
      { line: "I need you like a fish needs a <|REPLACE|>." },
      { line: "I never fall down I stand tall like the <|REPLACE|>." },
      { line: "I never need to shower I smell like a <|REPLACE|>." },
      { line: "I plant seeds of rhythm that grow into <|REPLACE|>" },
      { line: "I remember you. You used to be a <|REPLACE|>." },
      { line: "I rise to new heights I'm a master <|REPLACE|>." },
      { line: "I roll in the club decked out in <|REPLACE|>." },
      { line: "I rule the school they call me the <|REPLACE|>." },
      { line: "I soothe crying babies with the sound of my <|REPLACE|>." },
      { line: "I speak the truth, don't you <|REPLACE|>?" },
      { line: "I spit so fast they call me the <|REPLACE|>." },
      { line: "I swag when the sun rises and when it <|REPLACE|>." },
      { line: "I swim in jewels and bathe in <|REPLACE|>." },
      { line: "I taste sweet, as a delicious <|REPLACE|>." },
      { line: "I think you're wearing your mama's <|REPLACE|>." },
      { line: "I wake up, and eat rhymes like <|REPLACE|>." },
      { line: "I wanted a challenge but you're way too <|REPLACE|>." },
      { line: "I was out hustling while you were <|REPLACE|>." },
      { line: "I was raised in the tough part of <|REPLACE|>." },
      { line: "I will have my cake and eat it with your <|REPLACE|>." },
      { line: "I will have satisfaction I will have <|REPLACE|>." },
      { line: "I won a Nobel Prize for <|REPLACE|>." },
      { line: "I won't give you the finger I'll give you the <|REPLACE|>." },
      { line: "I won't say you're the worst. That's too <|REPLACE|>." },
      { line: "I'd call you trash but garbage ain't that <|REPLACE|>." },
      { line: "I'd usually expect to find you in a <|REPLACE|>." },
      { line: "I'll beat you all day and twice on <|REPLACE|>." },
      { line: "I'll eat you for breakfast with my <|REPLACE|>." },
      { line: "I'll eat you for dinner like a fire broiled <|REPLACE|>." },
      { line: "I'll give you the business and business is <|REPLACE|>." },
      { line: "I'll keep this short like your <|REPLACE|>." },
      { line: "I'll make you cower like a little <|REPLACE|>." },
      { line: "I'll mess you up make you miss <|REPLACE|>." },
      { line: "I'm a cosmic force so call me the Big <|REPLACE|>." },
      { line: "I'm a great rapper but you should hear me <|REPLACE|>." },
      { line: "I'm a hurricane. You're a <|REPLACE|>." },
      { line: "I'm a killer, with a heart of <|REPLACE|>." },
      { line: "I'm a legend, a regular <|REPLACE|>." },
      { line: "I'm a lion on the mic and you're a <|REPLACE|>." },
      { line: "I'm a master musician you're a small-time <|REPLACE|>." },
      { line: "I'm a thing of legend, a regular <|REPLACE|>." },
      { line: "I'm a trending topic the main story on <|REPLACE|>." },
      { line: "I'm a wild animal that you can never <|REPLACE|>." },
      { line: "I'm about to kick it up and add some <|REPLACE|>." },
      { line: "I'm all natural my rhymes come from <|REPLACE|>." },
      { line: "I'm always in fashion like a brand new <|REPLACE|>." },
      { line: "I'm an adult I'm a full fledged <|REPLACE|>." },
      { line: "I'm big time; you just got a big <|REPLACE|>." },
      { line: "I'm breaking down walls that block my <|REPLACE|>." },
      { line: "I'm busy hustling while you're busy <|REPLACE|>." },
      { line: "I'm calling your bluff cuz you've got <|REPLACE|>." },
      { line: "I'm capital-P Pretty like the capital-C <|REPLACE|>." },
      { line: "I'm clean as a surgeon. You're sloppy as a <|REPLACE|>." },
      { line: "I'm comin' for you so you best be <|REPLACE|>." },
      { line: "I'm coming after you so watch your <|REPLACE|>." },
      { line: "I'm cooking up bars that'll make you <|REPLACE|>." },
      { line: "I'm dangerous, like a <|REPLACE|>." },
      { line: "I'm done bein' nice this ain't no <|REPLACE|>." },
      { line: "I'm dressed to kill. You're dressed to <|REPLACE|>." },
      { line: "I'm falling asleep. Your verses are <|REPLACE|>." },
      { line: "I'm fast so use rewind to see my <|REPLACE|>." },
      { line: "I'm feelin' it, the beat is <|REPLACE|>." },
      { line: "I'm fluent in hustlin' conversational in <|REPLACE|>." },
      { line: "I'm flying high like a big ol' <|REPLACE|>" },
      { line: "I'm flying high like some kind of a <|REPLACE|>." },
      { line: "I'm French champagne you're a bottle of <|REPLACE|>." },
      { line: "I'm fresh and new you're as old as <|REPLACE|>." },
      { line: "I'm from the future my game is next-gen <|REPLACE|>." },
      { line: "I'm getting to you. You look all <|REPLACE|>." },
      { line: "I'm giant but gentle I wouldn't hurt a <|REPLACE|>." },
      { line: "I'm goin' national you're going to the <|REPLACE|>." },
      { line: "I'm going light speed you're driving a <|REPLACE|>." },
      { line: "I'm gonna put your sorry ass in a cone of <|REPLACE|>." },
      { line: "I'm gonna roast you like a <|REPLACE|>." },
      { line: "I'm gonna school you tuition's one billion <|REPLACE|>." },
      { line: "I'm gonna send you cryin' to your <|REPLACE|>." },
      { line: "I'm H B O, but you're <|REPLACE|>." },
      { line: "I'm here all day, hope you brought a <|REPLACE|>." },
      { line: "I'm here entertaining. You're out here <|REPLACE|>." },
      { line: "I'm here spittin' bars you're spittin' <|REPLACE|>." },
      { line: "I'm hunting for trophies but you're just a <|REPLACE|>." },
      { line: "I'm in the dictionary next to the word <|REPLACE|>." },
      { line: "I'm in your head. You're starting to <|REPLACE|>." },
      { line: "I'm just here, to say, <|REPLACE|>." },
      { line: "I'm knee deep in rhymes better get a <|REPLACE|>." },
      { line: "I'm known worldwide from Japan to <|REPLACE|>." },
      { line: "I'm known, from here to <|REPLACE|>." },
      { line: "I'm like a sports car you're like a <|REPLACE|>." },
      { line: "I'm making you cry like a little <|REPLACE|>." },
      { line: "I'm messin' you up makin' you feel <|REPLACE|>." },
      { line: "I'm no gangsta I'm the original <|REPLACE|>." },
      { line: "I'm not afraid of you. You remind me of a <|REPLACE|>." },
      { line: "I'm not afraid of you. You're like a <|REPLACE|>." },
      { line: "I'm not one for chitchat I like to <|REPLACE|>." },
      { line: "I'm not playing games I'm here to <|REPLACE|>." },
      { line: "I'm not safe for work you're an episode of <|REPLACE|>." },
      { line: "I'm on my way up, I could climb <|REPLACE|>." },
      { line: "I'm one in a million. You're one in <|REPLACE|>." },
      { line: "I'm practically magic, a regular <|REPLACE|>." },
      { line: "I'm renting space, inside your <|REPLACE|>." },
      { line: "I'm riding high on top of the <|REPLACE|>." },
      { line: "I'm set to rule so hand me the <|REPLACE|>." },
      { line: "I'm slamdunking rhymes like a <|REPLACE|>." },
      { line: "I'm slayin' these verses you don't leave a <|REPLACE|>." },
      { line: "I'm so clean. You're as dirty as your <|REPLACE|>." },
      { line: "I'm so good it's scary call me M C <|REPLACE|>." },
      { line: "I'm so good looking everybody says, '<|REPLACE|>!'" },
      { line: "I'm so heavy. You're as light as a <|REPLACE|>." },
      { line: "I'm so hot I got sponsored by <|REPLACE|>." },
      { line: "I'm so pumped for this great <|REPLACE|>." },
      { line: "I'm so rich in rhymes I could buy a <|REPLACE|>." },
      { line: "I'm so ripped I got muscles on my <|REPLACE|>." },
      { line: "I'm so strong because I eat all my <|REPLACE|>." },
      { line: "I'm so tough, they call me <|REPLACE|>." },
      { line: "I'm sorry to hear all you brought is <|REPLACE|>." },
      { line: "I'm spitting fire that's hotter than the <|REPLACE|>." },
      { line: "I'm stirring up beats with my big ol' <|REPLACE|>." },
      { line: "I'm sweet as honey. You're sour as <|REPLACE|>." },
      { line: "I'm sweeter than candy sharper than a <|REPLACE|>." },
      { line: "I'm taking you down like a train to <|REPLACE|>." },
      { line: "I'm taking you down like an ugly <|REPLACE|>." },
      { line: "I'm talkin' now, so listen up <|REPLACE|>." },
      { line: "I'm tearing up these streets like a <|REPLACE|>." },
      { line: "I'm tenacious, like a <|REPLACE|>." },
      { line: "I'm the best M C, in all of <|REPLACE|>." },
      { line: "I'm the cream of the crop I'm top shelf <|REPLACE|>." },
      { line: "I'm the cream of the crop you're a pot of <|REPLACE|>." },
      { line: "I'm the gamemaster playing you like <|REPLACE|>." },
      { line: "I'm the greatest as you can all <|REPLACE|>." },
      { line: "I'm the hunter, and you're the <|REPLACE|>." },
      { line: "I'm the law around here and you're a <|REPLACE|>." },
      { line: "I'm the main course, you're a <|REPLACE|>." },
      { line: "I'm the one, with the golden <|REPLACE|>." },
      { line: "I'm the punchline you're the <|REPLACE|>." },
      { line: "I'm the smartest in the world at <|REPLACE|>." },
      { line: "I'm the top dog, you're just a <|REPLACE|>." },
      { line: "I'm the Twenty-First century. You're the <|REPLACE|>." },
      { line: "I'm the ultimate ruler what I say becomes <|REPLACE|>." },
      { line: "I'm too hot, my body's made of <|REPLACE|>." },
      { line: "I'm workin' my magic, like <|REPLACE|>." },
      { line: "I'm, not much, of a <|REPLACE|>." },
      { line: "I'ma shatter you kid, like a <|REPLACE|>." },
      { line: "I've been known, to rhyme <|REPLACE|>." },
      { line: "I've got a time machine and I'm super <|REPLACE|>." },
      { line: "I've got mad knowledge I'm a real <|REPLACE|>." },
      { line: "I've got no use for people so <|REPLACE|>." },
      { line: "I've got rhymes, all you got is <|REPLACE|>." },
      { line: "I've got to be honest you're a huge <|REPLACE|>." },
      { line: "I've got your number and you're less than <|REPLACE|>." },
      { line: "I've heard better sounds coming out of a <|REPLACE|>." },
      { line: "I've learned all I know from watching <|REPLACE|>." },
      { line: "I've learned the ancient secrets of the <|REPLACE|>." },
      { line: "I've never met an opponent I couldn't <|REPLACE|>." },
      { line: "I've seen better faces on <|REPLACE|>." },
      { line: "I've taken your worst and I'm still <|REPLACE|>." },
      { line: "If I had money I wouldn't buy you a <|REPLACE|>." },
      { line: "If I knock you back, don't get <|REPLACE|>." },
      { line: "If I saw you online I would swipe <|REPLACE|>." },
      { line: "If I were you I wouldn't try any <|REPLACE|>." },
      { line: "If my rhymes were food they'd be <|REPLACE|>." },
      { line: "If you come at me you better bring <|REPLACE|>." },
      { line: "If you don't know you'd better <|REPLACE|>." },
      { line: "If you don't like regret get outta this <|REPLACE|>." },
      { line: "If you hate me, you'll hate my <|REPLACE|>." },
      { line: "If you like to take chances play <|REPLACE|>." },
      { line: "If you think you'll win you're straight-up <|REPLACE|>." },
      { line: "If you were a movie, you'd be <|REPLACE|>." },
      { line: "If you were a tree you'd be the <|REPLACE|>." },
      { line: "If you were dying of thirst I wouldn't give you a <|REPLACE|>." },
      { line: "If you were on TV you'd be <|REPLACE|>." },
      { line: "If you're gonna throw down do it <|REPLACE|>." },
      { line: "In high school I was voted Most <|REPLACE|>" },
      { line: "In professional wrestling you'd be the <|REPLACE|>." },
      { line: "In the dictionary your picture's under <|REPLACE|>." },
      { line: "In the human gene pool you're the <|REPLACE|>." },
      { line: "In the Star Wars universe you'd be <|REPLACE|>." },
      { line: "Is it true you prepare by listening to <|REPLACE|>?" },
      { line: "Is that you? I got a whiff of <|REPLACE|>." },
      { line: "Is this how you play? Acting like a <|REPLACE|>?" },
      { line: "Is your mama here? Tell'er you're <|REPLACE|>." },
      { line: "It ain't me, that's <|REPLACE|>." },
      { line: "It doesn't help that you're not very <|REPLACE|>." },
      { line: "It hurts me to say it but you're so <|REPLACE|>." },
      { line: "It must hurt, to be that <|REPLACE|>." },
      { line: "It's a showdown and my words are my <|REPLACE|>." },
      { line: "It's crazy the way you think you're <|REPLACE|>." },
      { line: "It's funny that you think you're <|REPLACE|>." },
      { line: "It's funny you think I'm a <|REPLACE|>." },
      { line: "It's hard not to choke when your rhymes are <|REPLACE|>." },
      { line: "It's hard to breathe cause your raps are <|REPLACE|>." },
      { line: "It's like this: I'm through bein' <|REPLACE|>." },
      { line: "It's my coronation call me the Queen of <|REPLACE|>." },
      { line: "It's my time, to inflict the <|REPLACE|>." },
      { line: "It's such a shame that you rhyme like a <|REPLACE|>." },
      { line: "It's true, my ego has its own <|REPLACE|>." },
      { line: "It's your wake up call! Time to get <|REPLACE|>." },
      { line: "Jump up, if you like my <|REPLACE|>." },
      { line: "Just come at me if you want to get <|REPLACE|>." },
      { line: "Just get out of here take a look at the <|REPLACE|>." },
      { line: "Just one question: What's up with your <|REPLACE|>." },
      { line: "Just put on your coat and run to the <|REPLACE|>." },
      { line: "Kanye and Drake they call me for <|REPLACE|>." },
      { line: "Keep your head, don't lose your <|REPLACE|>." },
      { line: "Knock-knock who's there it's me <|REPLACE|>." },
      { line: "Last night in bed your mom told me u were <|REPLACE|>." },
      { line: "Lemme tell you what's happenin' <|REPLACE|>." },
      { line: "Light the fuse and I'll explode like a <|REPLACE|>." },
      { line: "Lighting you up, like it's <|REPLACE|>." },
      { line: "Like Vader said to Luke I am your <|REPLACE|>." },
      { line: "Listen now, and shut your <|REPLACE|>." },
      { line: "Listen to you? I'd rather listen to <|REPLACE|>." },
      { line: "Listen up fool, I got no time to <|REPLACE|>." },
      { line: "Lock yourself in as I teach you about <|REPLACE|>." },
      { line: "Look at me now living the life to the <|REPLACE|>." },
      { line: "Look at you now thinking you're all <|REPLACE|>." },
      { line: "Look at you you're softer than <|REPLACE|>." },
      { line: "Look at you, you're dressed like <|REPLACE|>." },
      { line: "Look in my eyes and I'll turn you to <|REPLACE|>." },
      { line: "Look in the mirror, see a poor man's <|REPLACE|>." },
      { line: "Looks like you made it back from the <|REPLACE|>." },
      { line: "Maybe you'll understand when you're <|REPLACE|>." },
      { line: "Me and my crew we call ourselves the <|REPLACE|>." },
      { line: "Mess with me you'll get my foot in your <|REPLACE|>." },
      { line: "Money's on my mind. Your's is on <|REPLACE|>." },
      { line: "My angle is to turn you <|REPLACE|>." },
      { line: "My battle routine is brush floss and <|REPLACE|>." },
      { line: "My body's limber my brain's full of <|REPLACE|>." },
      { line: "My brain's so big my head's about to <|REPLACE|>." },
      { line: "My breath is foul but my bars are <|REPLACE|>." },
      { line: "My dates show me off like I'm a <|REPLACE|>." },
      { line: "My eye is on the prize because I'm <|REPLACE|>." },
      { line: "My face looks like I was hit by a <|REPLACE|>." },
      { line: "My fans call themselves The <|REPLACE|>." },
      { line: "My flow's my superpower call me Captain <|REPLACE|>." },
      { line: "My flow's so strong call me the Mississippi <|REPLACE|>." },
      { line: "My future's as bright as a burning <|REPLACE|>." },
      { line: "My game is rhymes your game is <|REPLACE|>." },
      { line: "My game's turbo charged-faster than a <|REPLACE|>." },
      { line: "My impact is massive like a raging <|REPLACE|>." },
      { line: "My lines are deep like an episode of <|REPLACE|>." },
      { line: "My lyrics are dreams come true make u <|REPLACE|>." },
      { line: "My lyrics are knowledge, better than <|REPLACE|>." },
      { line: "My mad rhymes will blow you to <|REPLACE|>." },
      { line: "My mom always says I'm her number one <|REPLACE|>." },
      { line: "My mouth is working like a lil' <|REPLACE|>." },
      { line: "My mouth's like a trumpet my brain's like a <|REPLACE|>." },
      { line: "My name's The Juggernaut cuz I never <|REPLACE|>." },
      { line: "My nickname for you is Lil' <|REPLACE|>." },
      { line: "My punchline's comin'. Better hide in a <|REPLACE|>." },
      { line: "My rap game is second only to my <|REPLACE|>." },
      { line: "My raps are so furious they caused a <|REPLACE|>." },
      { line: "My raps are so strong they could make a <|REPLACE|>." },
      { line: "My rhymes are a fist my verses are <|REPLACE|>." },
      { line: "My rhymes are delicate so handle with <|REPLACE|>." },
      { line: "My rhymes are fresh like a ripe new <|REPLACE|>." },
      { line: "My rhymes are sharper than a <|REPLACE|>." },
      { line: "My rhymes are so smooth you'll say <|REPLACE|>." },
      { line: "My rhymes are so sweet they're covered in <|REPLACE|>." },
      { line: "My rhymes are superb. Your beats are so <|REPLACE|>." },
      { line: "My rhymes are tasty as a sandwich with <|REPLACE|>." },
      { line: "My rhymes come express so they're never <|REPLACE|>." },
      { line: "My rhymes fly like rockets explode like <|REPLACE|>." },
      { line: "My rhymes melt on the tongue like <|REPLACE|>." },
      { line: "My rhymes will blast ya all the way to <|REPLACE|>." },
      { line: "My rhyming game is by far the <|REPLACE|>." },
      { line: "My robot hands are shaped to crush <|REPLACE|>." },
      { line: "My sick flow will knock you back to last <|REPLACE|>." },
      { line: "My skin is exfoliated my eyebrows are <|REPLACE|>." },
      { line: "My talent's so big we're running out of <|REPLACE|>." },
      { line: "My verse is legend, yours is <|REPLACE|>." },
      { line: "My verses are curses they'll put you <|REPLACE|>." },
      { line: "My verses come straight from the <|REPLACE|>." },
      { line: "My wallet's full like an overstuffed <|REPLACE|>." },
      { line: "My words are like paint I'm an artist like <|REPLACE|>." },
      { line: "My words are magical, call me <|REPLACE|>." },
      { line: "My words are presents I deliver like <|REPLACE|>." },
      { line: "My words are so deep you'll need a <|REPLACE|>." },
      { line: "My words are so fresh they smell like a <|REPLACE|>." },
      { line: "Never have I ever met someone so <|REPLACE|>." },
      { line: "No dress rehearsal, this is a <|REPLACE|>." },
      { line: "Nobody likes you, your rhymes are <|REPLACE|>." },
      { line: "Nobody's, gonna, push me <|REPLACE|>." },
      { line: "Not sweat that's talent coming out of my <|REPLACE|>." },
      { line: "Now run on home and cry in your <|REPLACE|>." },
      { line: "On your knees, before I get <|REPLACE|>." },
      { line: "On your mark. Get set. Let's <|REPLACE|>." },
      { line: "One look at you and I want to <|REPLACE|>." },
      { line: "One two three four five six <|REPLACE|>." },
      { line: "Only one can survive that means you get <|REPLACE|>." },
      { line: "Open your eyes, and see what's <|REPLACE|>." },
      { line: "Passin' you by, before you can <|REPLACE|>." },
      { line: "People like me more than they like <|REPLACE|>." },
      { line: "Pluggin' my nose cuz you smell like <|REPLACE|>." },
      { line: "Pump up the volume, the music's <|REPLACE|>." },
      { line: "Put down the fork you don't get no <|REPLACE|>." },
      { line: "Put up, or shut up, or <|REPLACE|>." },
      { line: "Quick question: Are you legit or a <|REPLACE|>?" },
      { line: "Quit looking at me with that face so <|REPLACE|>." },
      { line: "Rappin' isn't for you so maybe learn <|REPLACE|>." },
      { line: "Ready kid? Here comes another <|REPLACE|>." },
      { line: "Respect me now like you'd respect <|REPLACE|>." },
      { line: "Rhyming's not your game. Stick to <|REPLACE|>." },
      { line: "Right now I'm a seed but I'll soon be a <|REPLACE|>." },
      { line: "Rumor has it you attacked my <|REPLACE|>." },
      { line: "Run and find cover 'cuz I'm about to <|REPLACE|>." },
      { line: "Santa's got elves, I got my <|REPLACE|>." },
      { line: "Serving you up like a piece of <|REPLACE|>." },
      { line: "Smashin' your dreams like they're made of <|REPLACE|>." },
      { line: "So little talent, so much <|REPLACE|>." },
      { line: "Some say I'm flashy some say I'm <|REPLACE|>." },
      { line: "Something about you reminds me of <|REPLACE|>." },
      { line: "Sometimes you're the windshield others the <|REPLACE|>." },
      { line: "Sorry, but for you, it's game <|REPLACE|>." },
      { line: "Staring at your face is like staring at <|REPLACE|>." },
      { line: "Stealing this battle like I'm robbing a <|REPLACE|>." },
      { line: "Step aside 'cause you're gonna get <|REPLACE|>." },
      { line: "Step into my kitchen as I make you a <|REPLACE|>." },
      { line: "Step off before I hook up with your <|REPLACE|>." },
      { line: "Step to me and you're gonna get <|REPLACE|>." },
      { line: "Stop by the hospital 'cause your rhymes are <|REPLACE|>." },
      { line: "Struttin' like you're on the cover of <|REPLACE|>." },
      { line: "Success is my best friend failure is my <|REPLACE|>." },
      { line: "Suckas everywhere imitatin' my <|REPLACE|>." },
      { line: "Sure you got style if you're into <|REPLACE|>." },
      { line: "Sweat is pouring from all of your <|REPLACE|>." },
      { line: "Sweet like candy, I'm Mix Master <|REPLACE|>." },
      { line: "Take a deep breath I'm 'bout to wreck your <|REPLACE|>." },
      { line: "Take a step back before you get <|REPLACE|>." },
      { line: "Talk to the hand cuz my ears are <|REPLACE|>." },
      { line: "Talk to the hand cuz the face won't <|REPLACE|>." },
      { line: "That the best you got? Thought you were <|REPLACE|>." },
      { line: "That's all you got? That was pretty <|REPLACE|>." },
      { line: "That's how you do? Let me get you a <|REPLACE|>." },
      { line: "That's what you have to say? Well kiss my <|REPLACE|>." },
      { line: "That's your music? I thought it was a <|REPLACE|>." },
      { line: "The Avengers call me, Captain <|REPLACE|>." },
      { line: "The hurt's gonna happen you better be <|REPLACE|>." },
      { line: "The jury has its verdict you are guilty of <|REPLACE|>." },
      { line: "The math checks out I'm 100 percent <|REPLACE|>." },
      { line: "The name of my game is Rap 'til I <|REPLACE|>." },
      { line: "The one thing I love more than rhyming is <|REPLACE|>." },
      { line: "The only chance you got is one in <|REPLACE|>." },
      { line: "The pendulum's swinging, at your <|REPLACE|>." },
      { line: "The rhymes I paint are worth a thousand <|REPLACE|>." },
      { line: "The strong survive and you're looking <|REPLACE|>." },
      { line: "The sun is about to set on your <|REPLACE|>." },
      { line: "The things I despise more than you are <|REPLACE|>." },
      { line: "The train's left the station and you're <|REPLACE|>." },
      { line: "The word of the day boys and girls is <|REPLACE|>." },
      { line: "There are two things in life: death and <|REPLACE|>." },
      { line: "There's a planet named after me called <|REPLACE|>." },
      { line: "There's no happy ending this isn't <|REPLACE|>." },
      { line: "There's no hope for you. You're such a <|REPLACE|>." },
      { line: "They call me the Ruler, of <|REPLACE|>." },
      { line: "This ain't for people who got no <|REPLACE|>." },
      { line: "This battle is over as you'll see <|REPLACE|>." },
      { line: "This game ain't over until I see you <|REPLACE|>." },
      { line: "This is my jam, that is your <|REPLACE|>." },
      { line: "This is no Valentine this is a <|REPLACE|>." },
      { line: "This place is haunted by your <|REPLACE|>." },
      { line: "This will be over before you can <|REPLACE|>." },
      { line: "This won't end well for you just like <|REPLACE|>." },
      { line: "This'll be the outcome: You're gonna <|REPLACE|>." },
      { line: "Throw in the towel you've seen your last <|REPLACE|>." },
      { line: "To feed my rhymes I drink the blood of a <|REPLACE|>." },
      { line: "To reach the next level u gotta be <|REPLACE|>." },
      { line: "Try and hold me down I'll still <|REPLACE|>." },
      { line: "Try to keep up. Do you need a <|REPLACE|>?" },
      { line: "Trying to catch me is a wild goose <|REPLACE|>." },
      { line: "Trying to keep up? Let me get you a <|REPLACE|>." },
      { line: "U call yourself a pro? U can't even <|REPLACE|>." },
      { line: "U got no place to run, no place to <|REPLACE|>." },
      { line: "U look like u came from a botched <|REPLACE|>." },
      { line: "Understand this, you're nothing but a <|REPLACE|>." },
      { line: "Wah-ka-bam-zoo is my battle <|REPLACE|>." },
      { line: "Watch me flow I'm like a <|REPLACE|>." },
      { line: "Watch me work, I'm a master <|REPLACE|>." },
      { line: "Watch out! I'm gonna throw you like a <|REPLACE|>." },
      { line: "Wave your hands in the air like you just don't <|REPLACE|>." },
      { line: "We all disapprove, of your <|REPLACE|>." },
      { line: "We could be tight if your skills weren't so <|REPLACE|>." },
      { line: "Welcome to class I'm Professor <|REPLACE|>." },
      { line: "What day is it? It's the day you get <|REPLACE|>." },
      { line: "What's that? You got a frog in your <|REPLACE|>?" },
      { line: "What's wrong with you? Were you raised by <|REPLACE|>?" },
      { line: "Whatever you do I don't give a <|REPLACE|>." },
      { line: "When cookin' up rhymes I add some <|REPLACE|>." },
      { line: "When I cut myself shaving out flows <|REPLACE|>." },
      { line: "When I embarrass you does it make you feel <|REPLACE|>?" },
      { line: "When I hear your voice I want to <|REPLACE|>." },
      { line: "When I look at you I see an empty <|REPLACE|>." },
      { line: "When I say 'Hey' all the people shout <|REPLACE|>." },
      { line: "When I sense danger, I start to <|REPLACE|>." },
      { line: "When I start rhyming the people go <|REPLACE|>." },
      { line: "When I start rhyming they all get up to <|REPLACE|>." },
      { line: "When I think of you I think of <|REPLACE|>." },
      { line: "When I want a date I just jump on <|REPLACE|>." },
      { line: "When I'm at the mic no telling what I'll <|REPLACE|>." },
      { line: "When I'm done here I'm gonna go <|REPLACE|>." },
      { line: "When I'm done u won't remember your <|REPLACE|>." },
      { line: "When I'm on the mic you best look <|REPLACE|>." },
      { line: "When it's time to hang it up I won't <|REPLACE|>." },
      { line: "When life gives me lemons I make <|REPLACE|>." },
      { line: "When my words come at you your feet will <|REPLACE|>." },
      { line: "When you open your mouth out comes <|REPLACE|>." },
      { line: "When you rhyme you sound like a dying <|REPLACE|>." },
      { line: "When you're done here go back to <|REPLACE|>." },
      { line: "Where do you think you are? A <|REPLACE|>?" },
      { line: "While I work you're playing with a <|REPLACE|>." },
      { line: "Who do you think you are, <|REPLACE|>?" },
      { line: "Why are you so obsessed, with <|REPLACE|>?" },
      { line: "Why don't you go back to being a <|REPLACE|>?" },
      { line: "Why don't you leave? Go back to the <|REPLACE|>." },
      { line: "Word around town is that you got real <|REPLACE|>." },
      { line: "Word around town is you're afraid of <|REPLACE|>." },
      { line: "Word on the street is that you're full of <|REPLACE|>." },
      { line: "You ain't Busta Rhymes more like Busta <|REPLACE|>." },
      { line: "You ain't no Superman. Your power is <|REPLACE|>." },
      { line: "You ain't safe from my rhymes of <|REPLACE|>." },
      { line: "You are as overrated, as a <|REPLACE|>." },
      { line: "You aspire to greatness but you perspire <|REPLACE|>." },
      { line: "You attack me, you get messed <|REPLACE|>." },
      { line: "You better quit right now before you <|REPLACE|>." },
      { line: "You better recognize I'm the ultimate <|REPLACE|>." },
      { line: "You better sit down things are gonna get <|REPLACE|>." },
      { line: "You call me a failure but I've seen your <|REPLACE|>." },
      { line: "You came for me now I'm comin' for your <|REPLACE|>" },
      { line: "You can't be trusted to carry a <|REPLACE|>." },
      { line: "You can't beat me so don't even <|REPLACE|>." },
      { line: "You can't catch me I slip through the <|REPLACE|>." },
      { line: "You can't catch up you're moving like a <|REPLACE|>." },
      { line: "You can't hang with me, you'll <|REPLACE|>." },
      { line: "You can't hide from me not even in <|REPLACE|>." },
      { line: "You can't psyche me out, I'm <|REPLACE|>." },
      { line: "You can't rhyme your way out of a paper <|REPLACE|>." },
      { line: "You can't shake me, I'm made of <|REPLACE|>." },
      { line: "You come at me you're gonna get <|REPLACE|>." },
      { line: "You come here to play? I see you have a <|REPLACE|>." },
      { line: "You could write a book called 'How To <|REPLACE|>.'" },
      { line: "You couldn't touch me with a 10-foot <|REPLACE|>." },
      { line: "You don't belong here go back to your <|REPLACE|>." },
      { line: "You don't have flow it's more like <|REPLACE|>." },
      { line: "You don't look good like you saw a <|REPLACE|>." },
      { line: "You don't talk the talk. All I hear is <|REPLACE|>." },
      { line: "You done over there? Or you gonna keep <|REPLACE|>?" },
      { line: "You ever hear the one about the weak-ass <|REPLACE|>." },
      { line: "You fail so bad they had to call a <|REPLACE|>." },
      { line: "You feel those nerves inside your <|REPLACE|>?" },
      { line: "You feeling shy? Let me break the <|REPLACE|>." },
      { line: "You get less hype than the grand opening of a <|REPLACE|>." },
      { line: "You gonna stand here and say I'm a <|REPLACE|>." },
      { line: "You got no style got your clothes from a <|REPLACE|>." },
      { line: "You gotta come strong. I'm a battlin' <|REPLACE|>." },
      { line: "You guessed it--you're gonna get <|REPLACE|>." },
      { line: "You have an empty trophy case collectin' <|REPLACE|>." },
      { line: "You hear the sad news? You're about to <|REPLACE|>." },
      { line: "You hurt my eyes your face is so <|REPLACE|>." },
      { line: "You hurt my feelings I'll crush your <|REPLACE|>." },
      { line: "You know what they say: Payback's a <|REPLACE|>." },
      { line: "You like emojis? Well here's a <|REPLACE|>." },
      { line: "You look familiar like an odd-shaped <|REPLACE|>." },
      { line: "You look like you got caught in a <|REPLACE|>." },
      { line: "You look like you just drank some <|REPLACE|>." },
      { line: "You look like you were dressed by a <|REPLACE|>." },
      { line: "You make me laugh. You're just like a <|REPLACE|>." },
      { line: "You might make a good personal <|REPLACE|>." },
      { line: "You might want to slow down before you get <|REPLACE|>." },
      { line: "You need to realize you're only good at <|REPLACE|>." },
      { line: "You recycle your rhymes so I'll call you <|REPLACE|>." },
      { line: "You run your mouth I choose my words <|REPLACE|>." },
      { line: "You say you kill verses but you just commit <|REPLACE|>." },
      { line: "You see my face on the cover of <|REPLACE|>." },
      { line: "You seem to be lost. Now go back to the <|REPLACE|>." },
      { line: "You should apologize for bein' so <|REPLACE|>." },
      { line: "You should be ashamed. You rhyme so <|REPLACE|>." },
      { line: "You should give up rapping and take up <|REPLACE|>." },
      { line: "You should just go home so get in your <|REPLACE|>." },
      { line: "You should run away and join the <|REPLACE|>." },
      { line: "You smell like a bunch of rotting <|REPLACE|>." },
      { line: "You spend all your money on <|REPLACE|>." },
      { line: "You spit rhymes like your mouth's full of <|REPLACE|>." },
      { line: "You stepping to me? You must be <|REPLACE|>." },
      { line: "You take me down I'll give you a <|REPLACE|>." },
      { line: "You talkin to me? Or to my <|REPLACE|>?" },
      { line: "You think I'm big here you should see me in <|REPLACE|>." },
      { line: "You think you can come for me you little <|REPLACE|>?" },
      { line: "You think you're a cowboy but you're really a <|REPLACE|>." },
      { line: "You think you're bad? Don't make me <|REPLACE|>." },
      { line: "You think you're special you think you're <|REPLACE|>." },
      { line: "You tried to get in but the door went <|REPLACE|>!" },
      { line: "You try to match wits but can only match <|REPLACE|>." },
      { line: "You wanna throw down meet me at the <|REPLACE|>." },
      { line: "You want my autograph? Cuz you look <|REPLACE|>." },
      { line: "You want respect? You give me <|REPLACE|>." },
      { line: "You want some o' this? Well step on <|REPLACE|>." },
      { line: "You want to be me but you're just too <|REPLACE|>." },
      { line: "You'll go down in one hit: <|REPLACE|>!" },
      { line: "You're a beastly bear I'm an elegant <|REPLACE|>." },
      { line: "You're a rap herbivore you can't stomach <|REPLACE|>." },
      { line: "You're as helpless, as a tiny <|REPLACE|>." },
      { line: "You're as smooth as a three-legged <|REPLACE|>." },
      { line: "You're as useful as solar panels at <|REPLACE|>." },
      { line: "You're battling me? Well bring it my <|REPLACE|>." },
      { line: "You're boring me like a worn out <|REPLACE|>." },
      { line: "You're corn on the cob. I'm <|REPLACE|>." },
      { line: "You're down for the count so better stop <|REPLACE|>." },
      { line: "You're goin' nowhere so why ya wearin' a <|REPLACE|>?" },
      { line: "You're going down in a blaze of <|REPLACE|>." },
      { line: "You're gonna feel me right in the <|REPLACE|>." },
      { line: "You're lamer than a season of <|REPLACE|>." },
      { line: "You're like a cartoon. A regular <|REPLACE|>." },
      { line: "You're like a shelter puppy that nobody <|REPLACE|>." },
      { line: "You're lookin' stunned you can't grasp the <|REPLACE|>." },
      { line: "You're low on fuel better pump some <|REPLACE|>." },
      { line: "You're messin' with the wrong <|REPLACE|>." },
      { line: "You're not fit, to hold my <|REPLACE|>." },
      { line: "You're not in a pickle you're in deep <|REPLACE|>." },
      { line: "You're not on my level you're way too <|REPLACE|>." },
      { line: "You're not so hot. You're a regular <|REPLACE|>." },
      { line: "You're not the boss of me not even my <|REPLACE|>." },
      { line: "You're nothing to me like a little <|REPLACE|>." },
      { line: "You're riding my coattails like I'm a <|REPLACE|>." },
      { line: "You're right on the edge, of a <|REPLACE|>." },
      { line: "You're slippin' and slidin' as if standin' on <|REPLACE|>." },
      { line: "You're so boring. You remind me of <|REPLACE|>." },
      { line: "You're so broke you can't afford to <|REPLACE|>." },
      { line: "You're so weak you ain't worth my <|REPLACE|>." },
      { line: "You're so wrong to think you're <|REPLACE|>." },
      { line: "You're struttin' around like you're the <|REPLACE|>." },
      { line: "You're the Cowardly Lion, I'm <|REPLACE|>." },
      { line: "You're the flyswatter, I'm the <|REPLACE|>." },
      { line: "You're the one who's definitely <|REPLACE|>." },
      { line: "You're the student, I'm the <|REPLACE|>." },
      { line: "You're too weak, to use a <|REPLACE|>." },
      { line: "You're, more boring than <|REPLACE|>." },
      { line: "You've gone downhill you used to be <|REPLACE|>." },
      { line: "Your act's a ripoff you sound just like <|REPLACE|>." },
      { line: "Your brain's a weak processor it's running very <|REPLACE|>." },
      { line: "Your brain's so small it's the size of a <|REPLACE|>." },
      { line: "Your brand is expired. You're way too <|REPLACE|>." },
      { line: "Your breath is stinky did you just eat <|REPLACE|>." },
      { line: "Your busted rhymes are a crime against <|REPLACE|>." },
      { line: "Your face is my ball my words are my <|REPLACE|>." },
      { line: "Your face is so ugly you broke my <|REPLACE|>." },
      { line: "Your flow is jammed better give it a <|REPLACE|>." },
      { line: "Your flow's a disaster like a Category 5 <|REPLACE|>." },
      { line: "Your game is ancient, like <|REPLACE|>." },
      { line: "Your game is weak. It couldn't hurt a <|REPLACE|>." },
      { line: "Your hands are shaking vision's gettin' <|REPLACE|>." },
      { line: "Your head is as empty, as a <|REPLACE|>." },
      { line: "Your horoscope says you're going to fail <|REPLACE|>." },
      { line: "Your life so far, is just like <|REPLACE|>." },
      { line: "Your mama called she said you're bad at <|REPLACE|>." },
      { line: "Your mama's so dumb she says 'rap' rhymes with <|REPLACE|>." },
      { line: "Your new rapper name should be M C <|REPLACE|>." },
      { line: "Your rapping style, it's just so <|REPLACE|>." },
      { line: "Your raps are dying time to dig your own <|REPLACE|>." },
      { line: "Your raps are slower than the plot of <|REPLACE|>." },
      { line: "Your rhymes are a mess go get a <|REPLACE|>." },
      { line: "Your rhymes are about as deep as a <|REPLACE|>." },
      { line: "Your rhymes are bad 'cause you're dumb as a <|REPLACE|>." },
      { line: "Your rhymes are childish go play with your <|REPLACE|>." },
      { line: "Your rhymes are like a patchwork of <|REPLACE|>." },
      { line: "Your rhymes are like ads for <|REPLACE|>." },
      { line: "Your rhymes are limp as a bucket of <|REPLACE|>." },
      { line: "Your rhymes are old like a secondhand <|REPLACE|>." },
      { line: "Your rhymes are so wack they call you <|REPLACE|>." },
      { line: "Your rhymes are so weak they can't lift a <|REPLACE|>." },
      { line: "Your rhymes are soft, like <|REPLACE|>." },
      { line: "Your rhymes are tasteless like overcooked <|REPLACE|>." },
      { line: "Your rhymes aren't alive they're dead as <|REPLACE|>." },
      { line: "Your rhymes got me sleepy, need my <|REPLACE|>." },
      { line: "Your skills are close, but no <|REPLACE|>." },
      { line: "Your style is out of a fashion like an old <|REPLACE|>." },
      { line: "Your thrift store rhymes are secondhand <|REPLACE|>." },
      { line: "Your voice is annoying like a whiny <|REPLACE|>." },
      { line: "Your wordplay is wack your threads are <|REPLACE|>." },
      { line: "Your words are a mess like you wrote with <|REPLACE|>." },
    ];

    await Line.query().insert(linesData);

    console.log("Lines seeded");
  }
}

export default LineSeeder;
